apiVersion: v1
kind: Service
metadata:
  name: {{ include "rick-and-morty-app.fullname" . }}
spec:
  selector:
    app: {{ include "rick-and-morty-app.name" . }}
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: {{ .Values.service.type }}

