name: Kubernetes Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  setup-k8s-cluster:
    runs-on: self-hosted  # Using a self-hosted runner
    steps:
      - name: Set up Kubernetes cluster
        run: |
          sudo snap install microk8s --classic
          sudo microk8s.start

    env:
      APPLICATION: rick_and_morty_app
      NAMESPACE: default

  build-and-push:
    needs: setup-k8s-cluster
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/rick_and_morty_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/rick_and_morty_app:${{ github.sha }}
          platforms: linux/amd64,linux/arm64

  deploy-app:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Deploy to Kubernetes with Helm
        run: |
          helm upgrade rick-and-morty-app ./charts \
          --install \
          --set image.tag=${{ github.sha }} \
          --namespace default

  test-app:
    needs: deploy-app
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          curl http://app.local/healthcheck || exit 1

  save-artifact:
    needs: test-app
    runs-on: self-hosted
    steps:
      - name: Package Helm chart
        run: |
          helm package ./charts --version ${{ github.sha }}

      - name: Upload Helm chart artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-release-${{ github.sha }}
          path: ./rick-and-morty-app-${{ github.sha }}.tgz

      - name: Upload artifact to Nexus
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
          NEXUS_URL: 'http://nexus.yonif.net'
          NEXUS_REPOSITORY: 'rick_and_morty_app'
        run: |
          curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file ./rick-and-morty-app-${{ github.sha }}.tgz $NEXUS_URL/repository/$NEXUS_REPOSITORY/my-release/${{ github.sha }}/my-release-${{ github.sha }}.tgz
