
name: Kubernetes Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  setup-k8s-cluster:
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Set up Kubernetes cluster
        # Add steps to set up MicroK8s or any other Kubernetes cluster on the runner
        run: |
          # Example: Install MicroK8s
          sudo snap install microk8s --classic
          sudo microk8s.start

    env:
      APPLICATION: rick_and_morty_app
      NAMESPACE: default

  deploy-app:
    needs: setup-k8s-cluster
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build the Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rick_and_morty_app:latest .
        
      - name: Run docker container (in background) for build test
        run: docker run -p 5000:5000 rick_and_morty_app & 

      - name: Push the Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/rick_and_morty_app:latest

      - name: Deploy to Kubernetes with helm
        # Add steps to deploy the application to the Kubernetes cluster
        run: |
          helm upgrade rick-and-morty-app ./charts \
          --install \
          --namespace default
          

  test-app:
    needs: deploy-app
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Tests
        # Add steps to run tests against your application endpoints
        run: |
          # Example: Run tests using a test framework or curl commands
          curl http://localhost/healthcheck

