
name: Kubernetes Deployment Workflow

on:
  push:
    branches:
      - master

jobs:
  setup-k8s-cluster:
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Set up Kubernetes cluster
        # Add steps to set up MicroK8s or any other Kubernetes cluster on the runner
        run: |
          # Example: Install MicroK8s
          sudo snap install microk8s --classic
          sudo microk8s.start

    env:
      APPLICATION: rick_and_morty_app
      NAMESPACE: default

  deploy-app:
    needs: setup-k8s-cluster
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        run: |
          # Example: Build and push the Docker image
          docker build -t $APPLICATION .
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker tag $APPLICATION ${{ secrets.DOCKERHUB_USERNAME }}/$APPLICATION:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$APPLICATION:latest

      - name: Deploy to Kubernetes with helm
        # Add steps to deploy the application to the Kubernetes cluster
        run: |
          helm upgrade $APPLICATION ./ \
          --install \
          --namespace $NAMESPACE
          

  test-app:
    needs: deploy-app
    runs-on: self-hosted   # Specify the runner label for your self-hosted runner
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run Tests
        # Add steps to run tests against your application endpoints
        run: |
          # Example: Run tests using a test framework or curl commands
          curl http://localhost/healthcheck

